apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-operator-rolebinding
  namespace: tenant-a
subjects:
- kind: ServiceAccount
  name: ns-reconciler-tenant-a-ns-1-4
  namespace: config-management-system
- kind: ServiceAccount
  name: ns-reconciler-tenant-a-ns-2-4
  namespace: config-management-system
roleRef:
  kind: Role
  name: tenant-admin
  apiGroup: rbac.authorization.k8s.io
